version: 0.2

phases:
  install:
    commands:
      - echo Installing NGINX - echo apt-get install NGINX
      - sudo apt-get update
      - sudo apt-get install nginx -y

  build:
    command:
    - echo Build stared on date
    - cp index.html /var/www/html

  post_build:
    command:
      - echo Configuring NGINX

artifacts:
  files:
  -/var/www/html/index.html